local modpath = minetest.get_modpath("ks_flora")

dofile(modpath.."/nodes.lua")
dofile(modpath.."/mapgen.lua")
dofile(modpath.."/crafting.lua")
dofile(modpath.."/food.lua")
dofile(modpath.."/abm.lua")
dofile(modpath.."/grass.lua")
dofile(modpath.."/weaving.lua")
--dofile(modpath.."/leafdecay.lua")
